name: Publish To GitHub Release

on:
  push:
    tags:
    - '*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencie
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy
    - name: Build | Lint
      run: cargo clippy --manifest-path=src-tauri/Cargo.toml
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build | Compile
      run: cargo check --manifest-path=src-tauri/Cargo.toml
  test:
    name: Test
    strategy:
      matrix:
        os:
        - windows-latest
        rust:
        - stable
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build | Compile
      run: cargo test --manifest-path=src-tauri/Cargo.toml
  Publish:
    name: Publish
    permissions:
      contents: write
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup pnpm
      run: npm install -g pnpm
    - name: Install Dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Install | Next.js Requirements
      run: pnpm install
    - name: Build Tauri
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      with:
        tagName: __VERSION__
        releaseName: __VERSION__

  update:
    name: Update Version Checker
    needs: Publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Setup pnpm
      run: npm install -g pnpm
    - name: Install | Node.js Requirements
      run: pnpm install
    - name: Create Update
      run: pnpm run update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
